# Generated by Codex for the Raf's Souq backend scaffold.

import decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="categories/")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("phone", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="StoreSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("store_name", models.CharField(default="Raf's Souq", max_length=120)),
                ("support_email", models.EmailField(default="rafssouqgh@gmail.com", max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=40)),
                ("free_delivery_threshold", models.DecimalField(decimal_places=2, default=decimal.Decimal("750.00"), max_digits=10)),
                ("standard_delivery_fee", models.DecimalField(decimal_places=2, default=decimal.Decimal("45.00"), max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
            ],
            options={
                "verbose_name": "store setting",
                "verbose_name_plural": "store settings",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField()),
                ("details", models.JSONField(blank=True, default=list, help_text="List of product detail strings.")),
                ("tags", models.JSONField(blank=True, default=list, help_text="List of searchable tags.")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.00"))])),
                ("compare_at_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.00"))])),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("main_image", models.ImageField(blank=True, upload_to="products/main/")),
                ("badge", models.CharField(blank=True, choices=[("", "None"), ("New", "New"), ("Sale", "Sale"), ("Bestseller", "Bestseller"), ("Exclusive", "Exclusive"), ("Limited", "Limited")], default="", max_length=24)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")], default="draft", max_length=24)),
                ("is_featured", models.BooleanField(default=False)),
                ("track_inventory", models.BooleanField(default=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=3)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="store.category")),
            ],
            options={
                "ordering": ["-published_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(editable=False, max_length=32, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("address", models.CharField(max_length=240)),
                ("city", models.CharField(max_length=100)),
                ("postcode", models.CharField(blank=True, max_length=40)),
                ("country", models.CharField(default="GH", max_length=2)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("fulfilled", "Fulfilled"), ("cancelled", "Cancelled"), ("refunded", "Refunded")], default="pending", max_length=24)),
                ("payment_status", models.CharField(choices=[("unpaid", "Unpaid"), ("authorized", "Authorized"), ("paid", "Paid"), ("failed", "Failed"), ("refunded", "Refunded")], default="unpaid", max_length=24)),
                ("subtotal", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=10)),
                ("delivery_fee", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("notes", models.TextField(blank=True)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="store.customer")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="store.product")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("color_name", models.CharField(blank=True, max_length=80)),
                ("color_hex", models.CharField(blank=True, max_length=7)),
                ("size", models.CharField(blank=True, max_length=50)),
                ("sku", models.CharField(max_length=80, unique=True)),
                ("price_adjustment", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=10)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="store.product")),
            ],
            options={
                "ordering": ["product", "color_name", "size"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(help_text="Positive for stock added, negative for stock removed.")),
                ("reason", models.CharField(choices=[("restock", "Restock"), ("sale", "Sale"), ("return", "Return"), ("adjustment", "Adjustment"), ("damage", "Damage")], max_length=24)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_movements", to="store.product")),
                ("variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inventory_movements", to="store.productvariant")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(max_length=180)),
                ("sku", models.CharField(max_length=80)),
                ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="store.order")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_items", to="store.product")),
                ("variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_items", to="store.productvariant")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status", "slug"], name="store_produ_status_2ad4d8_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "status"], name="store_produ_categor_c8e9e6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_featured", "status"], name="store_produ_is_feat_0c3c7a_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_number"], name="store_order_order_n_aa22b2_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["email"], name="store_order_email_ba5851_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "payment_status"], name="store_order_status_c78689_idx"),
        ),
    ]
