# Generated by Django 5.2.16 on 2026-07-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_order_n_317f52_idx',
            old_name='store_order_order_n_aa22b2_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_email_9efbc4_idx',
            old_name='store_order_email_ba5851_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_status_83aac1_idx',
            old_name='store_order_status_c78689_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_status_b0e2b0_idx',
            old_name='store_produ_status_2ad4d8_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_categor_c5f89f_idx',
            old_name='store_produ_categor_c8e9e6_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_is_feat_3624fb_idx',
            old_name='store_produ_is_feat_0c3c7a_idx',
        ),
    ]
