import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/layout/LegalPage";

export const metadata: Metadata = { title: "Terms & Conditions", description: "Terms and conditions for shopping with Raf's Souq in Ghana.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <LegalPage eyebrow="Store policy" title="Terms & Conditions" updated="20 July 2026">
    <section><h2>1. About these terms</h2><p>These terms govern purchases made through the Raf&apos;s Souq website and our related customer-service channels. By placing an order, you confirm that the information you provide is accurate and that you accept these terms. Nothing here limits rights that cannot lawfully be excluded under Ghanaian law.</p><p>Raf&apos;s Souq is based in Accra, Ghana. Contact us at <a href="mailto:rafssouqgh@gmail.com">rafssouqgh@gmail.com</a>, by WhatsApp or phone on <a href="tel:+233558821133">+233 55 882 1133</a>, or through our <Link href="/contact">contact page</Link>.</p></section>
    <section><h2>2. Products and availability</h2><p>We aim to describe product colours, materials, sizing, and key characteristics accurately. Screen settings and lighting may cause slight colour differences. Products and variants are subject to availability, and adding an item to a bag does not reserve it.</p></section>
    <section><h2>3. Orders</h2><p>Your checkout submission is an offer to purchase. An order is accepted when Raf&apos;s Souq confirms it. We may contact you to verify details, correct an obvious error, or cancel an unavailable or suspicious order. If we cancel after receiving payment, the amount due will be returned through the appropriate method.</p></section>
    <section><h2>4. Prices and payment</h2><p>Prices are displayed in Ghana cedis unless stated otherwise. Payment is processed through Paystack or another method displayed at checkout. Payment-card and mobile-money credentials are handled by the payment provider and are not stored by Raf&apos;s Souq.</p><p>Please pay the complete amount shown. If a customer requests a discretionary refund before completing an order, a 5% service charge may be deducted where permitted and clearly communicated.</p></section>
    <section><h2>5. Processing and delivery</h2><p>Orders are normally processed within 1–3 business days. Checkout displays estimated regional delivery windows. Where checkout states that a rider fee is payable on delivery, that amount is paid separately to the rider and is not included in the online order total. Delivery estimates may change because of location, weather, carrier availability, public holidays, or events outside our reasonable control.</p><p>Customers must provide a complete address and reachable phone number. Additional delivery costs caused by an incorrect address, missed delivery, or requested redelivery may be charged to the customer.</p></section>
    <section><h2>6. Returns and exchanges</h2><ul><li>Within Accra, contact us and send an eligible item back within 24–48 hours of receiving it.</li><li>Outside Accra, send an eligible item back within 72 hours of receiving it.</li><li>Items must be unworn, unused, clean, undamaged, and returned in their original condition.</li><li>Return and exchange delivery fees are the customer&apos;s responsibility unless the item was faulty or incorrectly supplied.</li><li>Sale purchases are final unless applicable law requires otherwise.</li></ul><p>Items kept beyond the applicable return window, or items that are worn, dirty, damaged, altered, or appear used, may be refused. Contact us immediately with clear photographs if an item arrives faulty or incorrect.</p></section>
    <section><h2>7. Website use and intellectual property</h2><p>Store branding, photographs, text, graphics, and site design belong to Raf&apos;s Souq or their respective licensors. You may use the website for personal shopping only and must not misuse, copy, scrape, interfere with, or attempt unauthorised access to the website.</p></section>
    <section><h2>8. Liability</h2><p>To the extent permitted by law, Raf&apos;s Souq is not responsible for indirect or unforeseeable loss, third-party service interruptions, or delays outside our reasonable control. We remain responsible where liability cannot lawfully be limited.</p></section>
    <section><h2>9. Privacy</h2><p>Our <Link href="/privacy">Privacy Policy</Link> explains how personal information is collected, used, protected, and shared.</p></section>
    <section><h2>10. Governing law and changes</h2><p>These terms are governed by the laws of Ghana. We may update them when our services or legal obligations change. The version displayed when an order is placed applies to that order.</p></section>
  </LegalPage>;
}
