import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/layout/LegalPage";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Raf's Souq collects, uses, protects, and shares customer information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <LegalPage eyebrow="Your information" title="Privacy Policy" updated="20 July 2026">
    <section><h2>1. Who controls your information</h2><p>Raf&apos;s Souq, based in Accra, Ghana, controls the personal information described in this policy. Contact us at <a href="mailto:rafssouqgh@gmail.com">rafssouqgh@gmail.com</a>, <a href="tel:+233558821133">+233 55 882 1133</a>, or through our <Link href="/contact">contact page</Link>.</p></section>
    <section><h2>2. Information we collect</h2><ul><li>Contact details such as your name, email address, phone number, and delivery address.</li><li>Order information including products, colour, size, quantities, delivery choice, totals, and order status.</li><li>Messages, enquiries, reviews, and newsletter choices you send to us.</li><li>Technical and security information such as IP address, request time, browser information, and rate-limit records.</li><li>Cart, wishlist, and saved-checkout details stored locally in your browser. Checkout details are saved only when you select that option.</li></ul><p>Payment credentials are processed by Paystack or the payment provider shown at checkout. Raf&apos;s Souq does not receive or store full card or mobile-money authentication details.</p></section>
    <section><h2>3. Why we use information</h2><ul><li>To process, deliver, support, exchange, or refund orders.</li><li>To communicate about purchases and respond to enquiries.</li><li>To maintain inventory, prevent fraud, secure the website, and enforce rate limits.</li><li>To meet accounting, legal, and regulatory obligations.</li><li>To send marketing only where you have requested it or where otherwise permitted; you may opt out at any time.</li></ul><p>We collect and use only information reasonably needed for these stated purposes and aim to keep it accurate.</p></section>
    <section><h2>4. When information is shared</h2><p>We may share the minimum necessary information with Paystack and payment providers, delivery riders or courier partners, website/database hosting providers, email services, professional advisers, and authorities where required by law. These parties may use information only for the relevant service or legal purpose. We do not sell personal information.</p></section>
    <section><h2>5. Storage and retention</h2><p>Information may be processed by service providers inside or outside Ghana. Where cross-border processing occurs, we take reasonable steps to use providers and safeguards appropriate to the information. We retain order and transaction records for the period needed for fulfilment, support, accounting, disputes, fraud prevention, and legal obligations, then delete or anonymise information when it is no longer required.</p></section>
    <section><h2>6. Security</h2><p>We use access controls, encrypted connections, secure cookies, input validation, request limits, restricted administration, and vetted service providers. No internet service is completely risk-free, so customers should also protect their devices and account or payment credentials.</p></section>
    <section><h2>7. Your rights</h2><p>Subject to Ghana&apos;s Data Protection Act, 2012 (Act 843), you may ask whether we process your information, request access or correction, object to certain processing likely to cause unwarranted harm or distress, and stop direct marketing. You may also complain to Ghana&apos;s Data Protection Commission if you believe information has been mishandled.</p><p>Send a request to <a href="mailto:rafssouqgh@gmail.com">rafssouqgh@gmail.com</a>. We may verify your identity before acting on a request.</p></section>
    <section><h2>8. Children</h2><p>The store is not directed at children who can not lawfully make a purchase without a parent or guardian. A parent or guardian should place and manage such orders.</p></section>
    <section><h2>9. Updates</h2><p>We may update this policy when our practices, services, or legal obligations change. The latest version and update date will remain available on this page.</p></section>
  </LegalPage>;
}
